/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exo2 */

#ifndef _Included_Exo2
#define _Included_Exo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exo2
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Exo2_getPid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
