/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exo3And4 */

#ifndef _Included_Exo3And4
#define _Included_Exo3And4
#ifdef __cplusplus
extern "C" {
#endif
#undef Exo3And4_P
#define Exo3And4_P 10L
#undef Exo3And4_N
#define Exo3And4_N 10L
/*
 * Class:     Exo3And4
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Exo3And4_getPid
  (JNIEnv *, jclass);

/*
 * Class:     Exo3And4
 * Method:    fork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Exo3And4_fork
  (JNIEnv *, jclass);

/*
 * Class:     Exo3And4
 * Method:    cwait
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Exo3And4_cwait
  (JNIEnv *, jclass, jint);

/*
 * Class:     Exo3And4
 * Method:    exit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Exo3And4_exit
  (JNIEnv *, jclass, jint);

/*
 * Class:     Exo3And4
 * Method:    sleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Exo3And4_sleep
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
